"""Criação de coluna categoria em produtos

Revision ID: bcea04f19951
Revises: 5dc55e7591d5
Create Date: 2025-04-16 19:07:03.273509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcea04f19951'
down_revision = '5dc55e7591d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
